### ISSUE TITLE
[ER] Monitor App auto loads settings and starts

### ISSUE THREAD

**Issue by smoochy** [jgulick48/NiceHashProfitabilityCalculator#35]
Hi,

I would like to propose an enhancement request.

The Monitor should save the settings and does not ask for wallet address, worker name and storage type everytime. In addition the monitor should automatically start monitoring once it started.

Reason: I would like to put the monitor app into the autostart. So when my PC is started it automatically starts the application with the saved settings and starts monitoring.
Otherwise everytime the computer is booted up, I have to manually start the app, chose sotrage type and start monitoring.
This is especially helpful for rigs in remote destinations.

Maybe store this information in a simple config file or the monitoring app capable of dealing with command line variables?

Is there a difference for us users between SQLite and MySQL storage?

**Comment by jgulick48** [comment]
Most of the infrastructure for this is already in place when updating the application to relaunch and start.  I'll just modify it so if you close the app without hitting stop (which would happen in a crash or a reboot) it will start back up without prompts.

As for the Data type selection.  This was initially due to me going to support a local data instance but due to the amount of data recording sqlite isn't a feasible option. I'm going to hide this for now until I get stuff set up where you can deploy your own MySQL database if you want to.

Converted to Jira ticket https://jira.threegm.com/browse/NPC-17

**Comment by jgulick48** [comment]
This has been completed and should go out with the next release.

**Comment by jgulick48** [comment]
This change has been released with v1.0.0.74
