### ISSUE TITLE
How to completely removed data?

### ISSUE THREAD

**Issue by smoochy** [jgulick48/NiceHashProfitabilityCalculator#43]
I would like to completely reset settings and collected data.

I tried delete the Data folder. Did not work
I completely removed the NH Stats folder, redownloaded the latest version. Did not work.

Is there a way for me as a user to remove data and settings?

**Comment by jgulick48** [comment]
This has been added to the backlog and I hope to have an update out tonight with this and the bug you mentioned.

**Comment by jgulick48** [comment]
I have updated a way for this to work. In the Edit rig button, which is fixed in this next release, there will be an option to reset all rigs.  This will mark all rigs under your wallet address as inactive and will hide them all from the reports.  If you create a rig with the same name then it will mark that rig as active again but not have any historical data deleted.

If you create a new rig all your graphics card data that is tied to the card itself is transferred over to the new rig so no data is lost in this process.  I hope this helps resolve the issue that you were looking to fix.

**Comment by jgulick48** [comment]
Added in [v1.0.0.76](https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.76)
